---
deployment:
  tasks:
    - export DEPLOYPATH=/home1/zrjlxfte/softeem.ca
    - /bin/mkdir -p $DEPLOYPATH
    - /bin/cp -R /home1/zrjlxfte/repositories/softeem-dist/* $DEPLOYPATH
    - /bin/ls -la $DEPLOYPATH
